version: 2

multi-ecosystem-groups:
  flux-dependencies:
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Toronto
    labels:
      - dependencies

updates:
  - package-ecosystem: npm
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: flux-dependencies

  - package-ecosystem: github-actions
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: flux-dependencies
