export const cssVars = {
  font: {
    body: "--flux-font-body",
    mono: "--flux-font-mono",
    caption: "--flux-font-caption",
    bodySize: "--flux-font-body-size",
    lead: "--flux-font-lead",
    headingSm: "--flux-font-heading-sm",
    headingMd: "--flux-font-heading-md",
    headingLg: "--flux-font-heading-lg",
    headingXl: "--flux-font-heading-xl",
    display: "--flux-font-display",
    metric: "--flux-font-metric",
    regular: "--flux-font-regular",
    medium: "--flux-font-medium",
    bold: "--flux-font-bold",
    leading: "--flux-font-leading",
    tight: "--flux-font-tight",
  },

  color: {
    canvas: "--flux-color-canvas",
    surface: "--flux-color-surface",
    surfaceSubtle: "--flux-color-surface-subtle",
    surfaceElevated: "--flux-color-surface-elevated",
    text: "--flux-color-text",
    textMuted: "--flux-color-text-muted",
    textSubtle: "--flux-color-text-subtle",
    border: "--flux-color-border",
    borderStrong: "--flux-color-border-strong",
    accent: "--flux-color-accent",
    accentHover: "--flux-color-accent-hover",
    accentSoft: "--flux-color-accent-soft",
    accentForeground: "--flux-color-accent-foreground",
    success: "--flux-color-success",
    successHover: "--flux-color-success-hover",
    successSoft: "--flux-color-success-soft",
    successForeground: "--flux-color-success-foreground",
    warning: "--flux-color-warning",
    warningHover: "--flux-color-warning-hover",
    warningSoft: "--flux-color-warning-soft",
    warningForeground: "--flux-color-warning-foreground",
    danger: "--flux-color-danger",
    dangerHover: "--flux-color-danger-hover",
    dangerSoft: "--flux-color-danger-soft",
    dangerForeground: "--flux-color-danger-foreground",
    info: "--flux-color-info",
    infoHover: "--flux-color-info-hover",
    infoSoft: "--flux-color-info-soft",
    infoForeground: "--flux-color-info-foreground",
    focus: "--flux-color-focus",
  },
  space: {
    1: "--flux-space-1",
    2: "--flux-space-2",
    3: "--flux-space-3",
    4: "--flux-space-4",
    5: "--flux-space-5",
    6: "--flux-space-6",
    8: "--flux-space-8",
    10: "--flux-space-10",
    12: "--flux-space-12",
    16: "--flux-space-16",
  },
  radius: {
    sm: "--flux-radius-sm",
    md: "--flux-radius-md",
    lg: "--flux-radius-lg",
  },
  control: {
    sm: "--flux-control-sm",
    md: "--flux-control-md",
    lg: "--flux-control-lg",
  },
  motion: {
    fast: "--flux-motion-fast",
    normal: "--flux-motion-normal",
    easing: "--flux-motion-easing",
  },
} as const;

export const primitiveTokens = {
  font: {
    body: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    mono: '"SFMono-Regular", Consolas, "Liberation Mono", monospace',
    caption: "0.75rem",
    bodySize: "1rem",
    lead: "1.25rem",
    headingSm: "1.25rem",
    headingMd: "1.5rem",
    headingLg: "2rem",
    headingXl: "2.5rem",
    display: "4rem",
    metric: "1.75rem",
    regular: "400",
    medium: "600",
    bold: "700",
    leading: "1.6",
    tight: "1.15",
  },

  space: {
    1: "0.25rem",
    2: "0.5rem",
    3: "0.75rem",
    4: "1rem",
    5: "1.25rem",
    6: "1.5rem",
    8: "2rem",
    10: "2.5rem",
    12: "3rem",
    16: "4rem",
  },
  radius: {
    sm: "0.25rem",
    md: "0.25rem",
    lg: "0.5rem",
  },
  control: {
    sm: "2rem",
    md: "2.5rem",
    lg: "3rem",
  },
  motion: {
    fast: "100ms",
    normal: "180ms",
    easing: "cubic-bezier(0.2, 0, 0, 1)",
  },
} as const;

export const breakpoints = {
  sm: "40rem",
  md: "48rem",
  lg: "64rem",
  xl: "80rem",
  "2xl": "96rem",
} as const;
