import { LayersIcon } from "@varua/icons";
import type { SceneDefinition } from "../types.js";

export default {
  order: 4,
  label: "Deploy",
  brand: "Launchpad",
  headline: "Manage releases and services.",
  description: "Monitor deploys, view logs, and control releases.",
  prompt: "Switch services, adjust canary traffic, and view logs.",
  components: [
    "button",
    "callout",
    "card",
    "chart",
    "chart-legend",
    "chart-tooltip",
    "code",
    "code-block",
    "description-list",
    "dialog",
    "dropdown-menu",
    "field",
    "grid",
    "heading",
    "inline",
    "kbd",
    "progress",
    "select",
    "separator",
    "sidebar",
    "slider",
    "sparkline",
    "spinner",
    "stack",
    "status-badge",
    "switch",
    "table",
    "tabs",
    "text",
    "toggle",
    "tooltip",
  ],
  custom: "Fictional data and local state. UI uses public Flux components.",
  Icon: LayersIcon,
} satisfies SceneDefinition;
