import { GaugeIcon } from "@flux-ui/icons";
import type { SceneDefinition } from "../types.js";
export default {
  order: 0,
  label: "Finance",
  brand: "folio",
  headline: "A clearer view of the bigger picture.",
  description:
    "A working financial workspace: an overview, a searchable ledger, record details and team management.",
  prompt:
    "Explore Transactions and Team. Filter the ledger, edit a note, or record a local invitation.",
  components: [
    "avatar",
    "status-badge",
    "box",
    "button",
    "callout",
    "card",
    "chart",
    "combobox",
    "container",
    "data-table",
    "dialog",
    "drawer",
    "dropdown-menu",
    "empty-state",
    "field",
    "grid",
    "heading",
    "inline",
    "input",
    "input-group",
    "popover",
    "scroll-area",
    "select",
    "sidebar",
    "skeleton",
    "stack",
    "stat",
    "table",
    "tabs",
    "tag",
    "text",
    "textarea",
    "toast",
    "toggle",
    "toggle-group",
  ],
  custom:
    "Cash flow uses the public Chart. The payment-card illustration remains original artwork, not a PaymentCard API. All amounts, samples and transactions are fictional.",
  Icon: GaugeIcon,
} satisfies SceneDefinition;
