import { SparkIcon } from "@varua/icons";
import type { SceneDefinition } from "../types.js";

export default {
  order: 1,
  label: "Product",
  brand: "Beacon",
  headline: "Understand product performance.",
  description: "Explore usage, experiments, and feedback.",
  prompt: "Filter teams, inspect experiments, and adjust limits.",
  components: [
    "accordion",
    "button",
    "callout",
    "card",
    "chart",
    "chart-legend",
    "chart-tooltip",
    "combobox",
    "field",
    "grid",
    "heading",
    "icon-button",
    "inline",
    "meter",
    "pie-chart",
    "popover",
    "rating",
    "scatter-chart",
    "select",
    "slider",
    "stack",
    "stat",
    "status-badge",
    "switch",
    "tabs",
    "tag",
    "text",
    "toggle-group",
    "tooltip",
  ],
  custom: "Fictional data and local state. UI uses public Flux components.",
  Icon: SparkIcon,
} satisfies SceneDefinition;
