import { GaugeIcon } from "@flux-ui/icons";
import type { SceneDefinition } from "../types.js";

export default {
  order: 0,
  label: "Revenue",
  brand: "Northstar",
  headline: "Track revenue at a glance.",
  description: "Explore trends, accounts, and forecasts.",
  prompt: "Change dates, inspect charts, and open forecasts.",
  components: [
    "avatar",
    "breadcrumbs",
    "button",
    "card",
    "chart",
    "chart-legend",
    "chart-tooltip",
    "data-table",
    "date-picker",
    "dialog",
    "dropdown-menu",
    "field",
    "grid",
    "heading",
    "inline",
    "number-field",
    "pie-chart",
    "progress",
    "select",
    "sparkline",
    "stack",
    "stat",
    "status-badge",
    "text",
    "toggle-group",
  ],
  custom: "Fictional data and local state. UI uses public Flux components.",
  Icon: GaugeIcon,
} satisfies SceneDefinition;
