import { UsersIcon } from "@varua/icons";
import type { SceneDefinition } from "../types.js";

export default {
  order: 3,
  label: "Service",
  brand: "Relay",
  headline: "Keep support moving.",
  description: "Triage tickets, track SLAs, and reply to customers.",
  prompt: "Open a ticket, change priority, and send a reply.",
  components: [
    "accordion",
    "alert-dialog",
    "avatar",
    "button",
    "card",
    "collapsible",
    "date-time-picker",
    "field",
    "grid",
    "heading",
    "indicator",
    "inline",
    "progress",
    "radio-group",
    "stack",
    "status-badge",
    "stepper",
    "tag",
    "text",
    "textarea",
    "time-picker",
    "toast",
    "toolbar",
    "tree-view",
  ],
  custom: "Fictional data and local state. UI uses public Flux components.",
  Icon: UsersIcon,
} satisfies SceneDefinition;
